<script setup lang="ts">
import type { ContentPage } from '../../shared/content'
import { assetUrl, loadPage, renderLegacy } from '../utils/content'
const props=defineProps<{rootId:string}>();const panel=ref<ContentPage|null>(null);const image=ref<{src:string;alt:string}|null>(null);const opener=ref<HTMLElement|null>(null)
async function click(e:MouseEvent){const target=e.target as HTMLElement;const img=target.closest<HTMLImageElement>('img[data-lightbox]');if(img){e.preventDefault();opener.value=img;image.value={src:img.currentSrc||img.src,alt:img.alt};await nextTick();document.querySelector<HTMLElement>('.lightbox-close')?.focus();return}const a=target.closest<HTMLAnchorElement>('a[data-page-type="annotation"]');if(a&&!(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)&&e.button===0){e.preventDefault();opener.value=a;panel.value=await loadPage(a.dataset.pageId!);history.pushState({},'',`${location.pathname}?note=${a.dataset.pageId}`);await nextTick();document.querySelector<HTMLElement>('.panel-close')?.focus()}}
function close(){panel.value=null;image.value=null;if(location.search.includes('note='))history.replaceState({},'',location.pathname);nextTick(()=>opener.value?.focus())}
function key(e:KeyboardEvent){if(e.key==='Escape'&&(panel.value||image.value))close()}
onMounted(()=>{document.getElementById(props.rootId)?.addEventListener('click',click);addEventListener('keydown',key)});onBeforeUnmount(()=>{document.getElementById(props.rootId)?.removeEventListener('click',click);removeEventListener('keydown',key)})
</script>
<template><Teleport to="body"><aside v-if="panel" class="annotation-drawer" role="dialog" aria-modal="true" :aria-labelledby="`panel-${panel.id}`"><header class="drawer-header"><div><p class="eyebrow">Annotation</p><h2 :id="`panel-${panel.id}`">{{panel.title}}</h2></div><button class="panel-close icon-button" aria-label="Close annotation" @click="close">×</button></header><div class="drawer-body"><div class="legacy-content" v-html="renderLegacy(panel)"/></div><footer class="provenance"><NuxtLink :to="`/annotation/${panel.id}/`">Open permanent page</NuxtLink></footer></aside><div v-if="image" class="lightbox" role="dialog" aria-modal="true" aria-label="Fullscreen image"><button class="lightbox-close icon-button" aria-label="Close image" @click="close">×</button><img :src="image.src" :alt="image.alt"></div></Teleport></template>
