import { describe,expect,it } from 'vitest';import page from '../public/content/pages/burbank-notes-burbank-a.json';import { renderLegacy } from '../app/utils/content'
import metrePage from '../public/content/pages/among-notes-among-m.json'
import legacySearchPage from '../public/content/pages/eliot-search.json'
import traditionPage from '../public/content/pages/essays-swtradition.json'
import euripidesPage from '../public/content/pages/essays-sweuripides.json'
describe('server content renderer',()=>{it('rewrites annotation links to ordinary URLs',()=>{const html=renderLegacy(page as never);expect(html).toContain('href="/annotation/burbank-notes-title-n/"');expect(html).toContain('href="/annotation/burbank-notes-axletree-n/"');expect(html).not.toContain('href="title_N.htm"');expect(html).not.toContain('href="axletree_N.htm"')});it('embeds static annotation previews',()=>{const html=renderLegacy(page as never);expect(html).toContain('class="annotation-tooltip"');expect(html).toContain('role="tooltip"');expect(html).toContain('aria-describedby="annotation-tooltip-');expect(html).toContain('Click for the full annotation')});it('rewrites assets to canonical root paths',()=>{expect(renderLegacy(page as never)).toContain('/content/assets/')})})

describe('editorial asset replacements',()=>{it('renders reconstructed metre symbols without broken archival URLs',()=>{const html=renderLegacy(metrePage as never);expect(html).toContain('/editorial-assets/scansion/stressed.svg');expect(html).toContain('/editorial-assets/scansion/unstressed-long.svg');expect(html).toContain('/editorial-assets/scansion/unstressed-short.svg');expect(html).toContain('/editorial-assets/scansion/pause-dot.svg');expect(html).toContain('/editorial-assets/scansion/slur.svg');expect(html).not.toContain('/content/assets/images/stressed.gif')})})
describe('editorial asset replacements',()=>{it('omits an obsolete search badge while retaining its link text',()=>{const html=renderLegacy(legacySearchPage as never);expect(html).not.toContain('avmini.gif');expect(html).toContain('<strong>Search</strong>')})})
describe('Greek text recovery',()=>{it('renders missing Greek bitmaps as semantic Unicode text',()=>{const tradition=renderLegacy(traditionPage as never);expect(tradition).toContain('<span class="editorial-greek" lang="grc"');expect(tradition).toContain('ὁ δὲ νοῦς ἴσως');expect(tradition).not.toContain('greek1.gif');const euripides=renderLegacy(euripidesPage as never);expect(euripides).toContain('ἑξῆλθον δόμων');expect(euripides).toContain('οὐκ ἔστιν ἄλλη φρὴν μιαιφονωτέρα');expect(euripides).not.toContain('greek6.gif')})})
